# Generated by Django 6.1 on 2026-08-10 17:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('account_type', models.CharField(choices=[('cash', 'Cash'), ('checking', 'Bank Checking'), ('savings', 'Bank Savings'), ('credit_card', 'Credit Card'), ('other', 'Other')], default='cash', max_length=20)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('typical_direction', models.CharField(choices=[('IN', 'Income'), ('OUT', 'Expense'), ('BOTH', 'Both / Either')], default='BOTH', max_length=4)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('IN', 'Income (money in)'), ('OUT', 'Expense (money out)')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.CharField(blank=True, max_length=255)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=10)),
                ('interval', models.PositiveSmallIntegerField(default=1, help_text='Repeat every N periods, e.g. frequency=weekly + interval=2 = biweekly', validators=[django.core.validators.MinValueValidator(1)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for an indefinite schedule.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('generated_until', models.DateField(blank=True, editable=False, help_text='System-managed: the horizon date through which occurrences have been generated.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_transactions', to='ledger.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_transactions', to='ledger.category')),
            ],
            options={
                'ordering': ['-is_active', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('IN', 'Income (money in)'), ('OUT', 'Expense (money out)')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.CharField(blank=True, max_length=255)),
                ('due_date', models.DateField()),
                ('executed', models.BooleanField(default=False)),
                ('executed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='ledger.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='ledger.category')),
                ('recurring_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='ledger.recurringtransaction')),
            ],
            options={
                'ordering': ['due_date', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='recurringtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='recurring_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='recurringtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='recurring_end_date_after_start_date'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['due_date'], name='ledger_tran_due_dat_3c20b0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['executed'], name='ledger_tran_execute_e00b07_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'executed', 'due_date'], name='ledger_tran_account_223b25_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transaction_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('executed', False), ('executed_date__isnull', True)), models.Q(('executed', True), ('executed_date__isnull', False)), _connector='OR'), name='transaction_executed_date_consistency'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('recurring_source', 'due_date'), name='unique_occurrence_per_template_per_date'),
        ),
    ]
