# Generated by Django 6.1 on 2026-08-10 23:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='cut_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Day of month the statement closes (fecha de corte). Credit cards only.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='account',
            name='next_statement_cut_date',
            field=models.DateField(blank=True, editable=False, help_text='System-managed: the next date a statement will close for this card.', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='payment_due_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Day of the following month payment is due. Credit cards only.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='ledger.account'),
        ),
        migrations.CreateModel(
            name='CreditCardStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cut_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('statement_balance', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='ledger.account')),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='statement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_expenses', to='ledger.creditcardstatement'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('executed', False), ('account__isnull', False), _connector='OR'), name='transaction_executed_requires_account'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='in_leg',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_as_destination', to='ledger.transaction'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='out_leg',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_as_source', to='ledger.transaction'),
        ),
        migrations.AddField(
            model_name='creditcardstatement',
            name='payment_obligation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_card_statement', to='ledger.transfer'),
        ),
    ]
