# Generated by Django 6.1 on 2026-08-11 00:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_transfer_account_cut_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cut_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Day of month the statement closes (fecha de corte). Credit cards only.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='account',
            name='payment_due_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Day of the following month payment is due. Credit cards only.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
