# Generated by Django 6.1 on 2026-08-12 01:04

import django.core.validators
import ledger.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_alter_account_cut_day_alter_account_payment_due_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=ledger.models.attachment_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'heic', 'doc', 'docx', 'xls', 'xlsx', 'txt']), ledger.models.validate_attachment_size]),
        ),
    ]
